// <auto-generated />
using System;
using BackHorodatage;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace BackHorodatage.Migrations
{
    [DbContext(typeof(PostgreSqlContext))]
    partial class PostgreSqlContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("BackHorodatage.Models.HorodatageUser", b =>
                {
                    b.Property<int>("IdHorodatage")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdHorodatage"));

                    b.Property<DateTime>("DateArrival")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("DateDeparture")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("IdUser")
                        .HasColumnType("integer");

                    b.Property<int?>("UserIdUser")
                        .HasColumnType("integer");

                    b.HasKey("IdHorodatage");

                    b.HasIndex("UserIdUser");

                    b.ToTable("HorodatageUser", "public");
                });

            modelBuilder.Entity("BackHorodatage.Models.Login", b =>
                {
                    b.Property<int>("IdLogin")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdLogin"));

                    b.Property<string>("Password")
                        .HasColumnType("text");

                    b.Property<string>("Pseudo")
                        .HasColumnType("text");

                    b.Property<int?>("UserIdUser")
                        .HasColumnType("integer");

                    b.HasKey("IdLogin");

                    b.HasIndex("UserIdUser");

                    b.ToTable("Login");
                });

            modelBuilder.Entity("BackHorodatage.Models.User", b =>
                {
                    b.Property<int>("IdUser")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdUser"));

                    b.Property<string>("Email")
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Nom")
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Poste")
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Prenom")
                        .HasColumnType("varchar(100)");

                    b.HasKey("IdUser");

                    b.ToTable("User", "public");
                });

            modelBuilder.Entity("BackHorodatage.Models.HorodatageUser", b =>
                {
                    b.HasOne("BackHorodatage.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserIdUser");

                    b.Navigation("User");
                });

            modelBuilder.Entity("BackHorodatage.Models.Login", b =>
                {
                    b.HasOne("BackHorodatage.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserIdUser");

                    b.Navigation("User");
                });
#pragma warning restore 612, 618
        }
    }
}
